apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmmottak
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  kafka:
    pool: nav-dev
  azure:
    application:
      enabled: true
      tenant: trygdeetaten.no
  vault:
    enabled: true
    paths:
      - kvPath: /kv/preprod/fss/syfosmmottak/teamsykmelding
        mountPath: /secrets/default
      - kvPath: serviceuser/data/dev/srvsyfosmmottak
        mountPath: /secrets/serviceuser
  webproxy: true
  envFrom:
    - secret: syfosmmottak-redis-password
  env:
    - name: SUBSCRIPTION_ENDPOINT_URL
      value: https://wasapp-q1.adeo.no/nav-emottak-eletter-web/services/
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: MQ_HOST_NAME
      value: b27apvl222.preprod.local
    - name: MQ_PORT
      value: '1413'
    - name: MQ_GATEWAY_NAME
      value: MQLS04
    - name: MQ_CHANNEL_NAME
      value: Q1_SYFOSMMOTTAK
    - name: MQ_SYFOSERVICE_QUEUE_NAME
      value: QA.Q1_EIA_SYFO_OUTBOUND
    - name: MQ_INPUT_QUEUE_NAME
      value: QA.Q1_SYFOSMMOTTAK.INPUT
    - name: MQ_INPUT_BOQ_QUEUE_NAME
      value: Q1_SYFOSMMOTTAK.INPUT_BOQ
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.preprod.local/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: HELSENETT_ENDPOINT_URL
      value: https://syfohelsenettproxy.nais.preprod.local
    - name: HELSENETT_SCOPE
      value: api://dev-fss.teamsykmelding.syfohelsenettproxy/.default
