apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmmottak
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 2048Mi
    requests:
      cpu: 250m
      memory: 1536Mi
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
      tenant: nav.no
  vault:
    enabled: true
    paths:
      - kvPath: /kv/prod/fss/syfosmmottak/teamsykmelding
        mountPath: /secrets/default
      - kvPath: serviceuser/data/prod/srvsyfosmmottak
        mountPath: /secrets/serviceuser
      - kvPath: /kv/prod/fss/syfosmmottak/teamsykmelding
        mountPath: /var/run/secrets/nais.io/vault
  webproxy: true
  envFrom:
    - secret: syfosmmottak-redis-password
  env:
    - name: SUBSCRIPTION_ENDPOINT_URL
      value: https://wasapp.adeo.no/nav-emottak-eletter-web/services/
    - name: MQ_HOST_NAME
      value: a01apvl271.adeo.no
    - name: MQ_PORT
      value: '1414'
    - name: MQ_GATEWAY_NAME
      value: MPLS04
    - name: MQ_CHANNEL_NAME
      value: P_SYFOSMMOTTAK
    - name: MQ_INPUT_QUEUE_NAME
      value: QA.P_SYFOSMMOTTAK.INPUT
    - name: MQ_INPUT_BOQ_QUEUE_NAME
      value: P_SYFOSMMOTTAK.INPUT_BOQ
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.nais.adeo.no/graphql
    - name: HELSENETT_ENDPOINT_URL
      value: https://syfohelsenettproxy.nais.adeo.no
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: HELSENETT_SCOPE
      value: api://prod-fss.teamsykmelding.syfohelsenettproxy/.default
    - name: SYKMELDING_VEDLEGG_BUCKET_NAME
      value: teamsykmelding-sykmelding-vedlegg-bucket-prod
    - name: KUHR_SAR_API_SCOPE
      value: api://prod-fss.teamkuhr.kuhr-sar-api/.default
    - name: KUHR_SAR_API_URL
      value: https://kuhr-sar-api.nais.adeo.no
    - name: SYFOSMREGLER_API_SCOPE
      value: api://prod-fss.teamsykmelding.syfosmregler/.default
