apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmmottak
  namespace: default
  labels:
    team: {{team}}
spec:
  image: "docker.pkg.github.com/navikt/syfosmmottak:{{tag}}"
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
  env:
    - name: ARBEIDSFORDELING_V1_ENDPOINT_URL
      value: https://app-q1.adeo.no/norg2/ws/Arbeidsfordeling/v1
    - name: SUBSCRIPTION_ENDPOINT_URL
      value: https://wasapp-q1.adeo.no/nav-emottak-eletter-web/services/
    - name: SECURITY_TOKEN_SERVICE_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    - name: PERSON_V3_ENDPOINT_URL
      value: https://wasapp-q1.adeo.no/tpsws/ws/Person/v3
    - name: AKTOR_REGISTER_V1_URL
      value: https://app-q1.adeo.no/aktoerregister/api/v1
    - name: KAFKA_BOOTSTRAP_SERVERS_URL
      value: SSL://b27apvl00045.preprod.local:8443,SSL://b27apvl00046.preprod.local:8443,SSL://b27apvl00047.preprod.local:8443
    - name: MQ_HOST_NAME
      value: b27apvl177.preprod.local
    - name: MQ_PORT
      value: '1413'
    - name: MQ_GATEWAY_NAME
      value: MQ1LSC04
    - name: MQ_CHANNEL_NAME
      value: Q1_SYFOSMMOTTAK
    - name: MQ_SYFOSERVICE_QUEUE_NAME
      value: QA.Q1_EIA_SYFO_OUTBOUND
    - name: MQ_INPUT_QUEUE_NAME
      value: QA.Q1_SYFOSMMOTTAK.INPUT
    - name: MQ_APPREC_QUEUE_NAME
      value: QA.Q414.IU03_UTSENDING
    - name: MQ_INPUT_BOQ_QUEUE_NAME
      value: Q1_SYFOSMMOTTAK.INPUT_BOQ
    - name: APPLICATION_THREADS
      value: '1'