apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "syfosmmottak"
  namespace: "default"
  labels:
    team: "teamsykefravr"
spec:
  image: "repo.adeo.no:5443/syfo/syfosmmottak:@@VERSION@@"
  replicas:
    min: 1
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 512Mi
  vault:
    enabled: true
  env:
    - name: CONFIG_FILE
      value: "config-prod.json"
