apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfosmmottak
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  gcp:
    sqlInstances:
      - name: syfosmmottak-instance
        type: POSTGRES_14
        tier: db-custom-1-3840
        databases:
          - name: syfosmmottak
            envVarPrefix: DB
        diskAutoresize: true
        highAvailability: true
        diskType: SSD
        insights:
          enabled: true
  image: {{ image }}
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 1
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 1024Mi
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
      tenant: nav.no
  accessPolicy:
    outbound:
      rules:
        - application: syfosmregler
        - application: clamav
          namespace: nais-system
        - application: syfohelsenettproxy
        - application: smtss
      external:
        - host: smgcp-proxy.prod-fss-pub.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
        - host: mpls04.adeo.no
          ports:
            - port: 1414
  envFrom:
    - secret: srvsyfosmmottak-secrets
  filesFrom:
    - mountPath: /var/run/secrets
      secret: sykmeldingvedlegg-google-creds
  secureLogs:
    enabled: true
  env:
    - name: MQ_HOST_NAME
      value: mpls04.adeo.no
    - name: MQ_PORT
      value: '1414'
    - name: MQ_GATEWAY_NAME
      value: MPLS04
    - name: MQ_CHANNEL_NAME
      value: P_SYFOSMMOTTAK
    - name: MQ_INPUT_QUEUE_NAME
      value: QA.P_SYFOSMMOTTAK.INPUT
    - name: MQ_INPUT_BOQ_QUEUE_NAME
      value: P_SYFOSMMOTTAK.INPUT_BOQ
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: HELSENETT_ENDPOINT_URL
      value: http://syfohelsenettproxy
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: HELSENETT_SCOPE
      value: api://prod-gcp.teamsykmelding.syfohelsenettproxy/.default
    - name: SYKMELDING_VEDLEGG_BUCKET_NAME
      value: teamsykmelding-sykmelding-vedlegg-bucket-prod
    - name: SMGCP_PROXY_SCOPE
      value: api://prod-fss.teamsykmelding.smgcp-proxy/.default
    - name: SMGCP_PROXY_URL
      value: https://smgcp-proxy.prod-fss-pub.nais.io
    - name: SYFOSMREGLER_API_SCOPE
      value: api://prod-gcp.teamsykmelding.syfosmregler/.default
    - name: SMTSS_API_SCOPE
      value: api://prod-gcp.teamsykmelding.smtss/.default
