apiVersion: "nais.io/v1alpha1"
kind: Application
metadata:
  name: syfosmmottak
  namespace: default
  labels:
    team: "teamsykefravr"
spec:
  name: "syfosmmottak"
  image: "repo.adeo.no:5443/syfo/syfosmmottak:@@VERSION@@"
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /is_alive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /is_ready
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
  prometheus:
    enabled: true
    path: /prometheus
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  vault:
    enabled: true
  env:
  - name: ARBEIDSFORDELING_V1_ENDPOINT_URL
    value: {{ARBEIDSFORDELING_V1_ENDPOINT_URL}}
  - name: SUBSCRIPTION_ENDPOINT_URL
    value: {{SUBSCRIPTION_ENDPOINT_URL}}
  - name: SECURITY_TOKEN_SERVICE_URL
    value: {{SECURITY_TOKEN_SERVICE_URL}}
  - name: PERSON_V3_ENDPOINT_URL
    value: {{PERSON_V3_ENDPOINT_URL}}
  - name: AKTOR_REGISTER_V1_URL
    value: {{AKTOR_REGISTER_V1_URL}}
  - name: KAFKA_BOOTSTRAP_SERVERS_URL
    value: {{KAFKA_BOOTSTRAP_SERVERS_URL}}
  - name: MQ_HOST_NAME
    value: {{MQ_HOST_NAME}}
  - name: MQ_PORT
    value: '{{MQ_PORT}}'
  - name: MQ_GATEWAY_NAME
    value: {{MQ_GATEWAY_NAME}}
  - name: MQ_CHANNEL_NAME
    value: {{MQ_CHANNEL_NAME}}
  - name: MQ_SYFOSERVICE_QUEUE_NAME
    value: {{MQ_SYFOSERVICE_QUEUE_NAME}}
  - name: MQ_INPUT_QUEUE_NAME
    value: {{MQ_INPUT_QUEUE_NAME}}
  - name: MQ_APPREC_QUEUE_NAME
    value: {{MQ_APPREC_QUEUE_NAME}}
  - name: MQ_INPUT_BOQ_QUEUE_NAME
    value: {{MQ_INPUT_BOQ_QUEUE_NAME}}
  - name: APPLICATION_THREADS
    value: {{APPLICATION_THREADS}}
