apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: teamsykefravr
  name: syfosmmottak-redis
  namespace: default
spec:
  image: redis:5-alpine
  port: 6379
  replicas:
    min: 1
    max: 4
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 512Mi
  service:
    port: 6379