apiVersion: unleash.nais.io/v1
kind: ApiToken
metadata:
  name: syfosmmottak
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  unleashInstance:
    apiVersion: unleash.nais.io/v1
    kind: RemoteUnleash
    name: teamsykmelding
  secretName: syfosmmottak-unleash-api-token

  # Specify which environment the API token should be created for.
  # Can be one of: development, or production.
  environment: {{environment}}
