package no.nav.syfo.apprec

import no.nav.syfo.client.RuleInfo

enum class ApprecError(val v: String, val dn: String, val s: String, val ruleinfo: RuleInfo) {
    INVALID_FNR_SIZE("X99", "Pasienten sitt fødselsnummer eller D-nummer er ikke 11 tegn.", "2.16.578.1.12.4.1.1.8221", RuleInfo("INVALID_FNR_SIZE")),
    INVALID_FNR("X99", "Fødselsnummer/D-nummer kan passerer ikke modulus 11",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("INVALID_FNR")),
    YOUNGER_THAN_13("X99", "Hele sykmeldingsperioden er før bruker har fylt 13 år. Pensjonsopptjening kan starte fra 13 år.",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("YOUNGER_THAN_13")),
    PATIENT_OVER_70_YEARS("X99", "Hele sykmeldingsperioden er etter at bruker har fylt 70 år. Dersom bruker fyller 70 år i perioden skal sykmelding gå gjennom på vanlig måte.",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("PATIENT_OVER_70_YEARS")),
    UNKNOWN_DIAGNOSECODE_TYPE("X99", "Ukjent diagnosekode type",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("UNKNOWN_DIAGNOSECODE_TYPE")),
    ICPC_2_Z_DIAGNOSE("X99", "Hvis hoveddiagnose er Z-diagnose (ICPC-2), avvises meldingen.",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("ICPC_2_Z_DIAGNOSE")),
    MAIN_DIAGNOSE_MISSING_AND_MISSING_REASON("X99", "Hvis hoveddiagnose mangler og det ikke er angitt annen lovfestet fraværsgrunn, avvises meldingen",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("MAIN_DIAGNOSE_MISSING_AND_MISSING_REASON")),
    INVALID_KODEVERK_FOR_MAIN_DIAGNOSE("X99", "Hvis kodeverk ikke er angitt eller korrekt for hoveddiagnose, avvises meldingen.",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("INVALID_KODEVERK_FOR_MAIN_DIAGNOSE")),
    INVALID_KODEVERK_FOR_BI_DIAGNOSE("X99", "Hvis kodeverk ikke er angitt eller korrekt for bidiagnose, avvises meldingen.",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("INVALID_KODEVERK_FOR_BI_DIAGNOSE")),
    NO_MEDICAL_OR_WORKPLACE_RELATED_REASONS("X99", "Hvis medisinske eller arbeidsplassrelaterte årsaker ved 100% sykmelding ikke er oppgitt og sykmeldingen ikke er \"forenklet\"",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("NO_MEDICAL_OR_WORKPLACE_RELATED_REASONS")),
    MISSING_REQUIRED_DYNAMIC_QUESTIONS("X99", "Hvis utdypende opplysninger om medisinske eller arbeidsplassrelaterte årsaker ved 100% sykmelding ikke er oppgitt ved 8.17, 39 uker før regelsettversjon \"2\" er innført skal sykmeldingen avvises",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("MISSING_REQUIRED_DYNAMIC_QUESTIONS")),
    MISSING_REQUIRED_MEDICAL_REASON("X99", "Hvis utdypende opplysninger om medisinske eller arbeidsplassrelaterte årsaker ved 100% sykmelding ikke er oppgitt ved 8.17, 39 uker før regelsettversjon \"2\" er innført skal sykmeldingen avvise",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("MISSING_REQUIRED_MEDICAL_REASON")),
    INVALID_RULESET_VERSION("X99", "Hvis regelsettversjon som er angitt i fagmelding ikke eksisterer så skal meldingen returneres",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("INVALID_RULESET_VERSION")),
    MISSING_REQUIRED_DYNAMIC_QUESTIONS_AFTER_RULE_SET_VERSION_2("X99", "Hvis utdypende opplysninger om medisinske eller arbeidsplassrelaterte årsaker ved 100% sykmelding ikke er oppgitt ved 7.17, 39 uker etter innføring av regelsettversjon \"2\" så skal sykmeldingen avvises",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("MISSING_REQUIRED_DYNAMIC_QUESTIONS_AFTER_RULE_SET_VERSION_2")),
    DUPLICATE("54", "Duplikat! - Denne legeerklæringen meldingen er mottatt tidligere. Skal ikke sendes på nytt.",
            "2.16.578.1.12.4.1.1.8222", RuleInfo("DUPLICATE")),
    BEHANDLER_NOT_IN_HPR("X99", "Behandler ikke registrert i HPR",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("BEHANDLER_NOT_IN_HPR")),
    BEHANDLER_NOT_VALDIG_IN_HPR("X99", "Behandler er ikke gyldig i HPR på konsultasjonstidspunkt..",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("BEHANDLER_NOT_VALDIG_IN_HPR")),
    BEHANDLER_NOT_VALID_AUTHORIZATION_IN_HPR("X99", "Behandler har ikkje gylding autorisasjon i HPR",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("BEHANDLER_NOT_VALID_AUTHORIZATION_IN_HPR")),
    BEHANDLER_SUSPENDED("X99", "Behandler er suspendert av NAV på konsultasjonstidspunkt",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("BEHANDLER_SUSPENDED")),
    SIGNATURE_DATE_AFTER_RECEIVED_DATE("X99", "Behandlet dato (felt 12.1) er etter dato for mottak av sykmeldingen.",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("SIGNATURE_DATE_AFTER_RECEIVED_DATE")),
    NO_PERIOD_PROVIDED("X99", "Hvis ingen perioder er oppgitt skal sykmeldingen avvises.",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("NO_PERIOD_PROVIDED")),
    TO_DATE_BEFORE_FROM_DATE("X99", "Hvis tildato for en periode ligger før fradato avvises meldingen og hvilken periode det gjelder oppgis.",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("TO_DATE_BEFORE_FROM_DATE")),
    OVERLAPPING_PERIODS("X99", "Hvis en eller flere perioder er overlappende avvises meldingen og hvilken periode det gjelder oppgis.",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("OVERLAPPING_PERIODS")),
    GAP_BETWEEN_PERIODS("X99", "Hvis det finnes opphold mellom perioder i sykmeldingen avvises meldingen.",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("GAP_BETWEEN_PERIODS")),
    BACKDATED_MORE_THEN_8_DAYS_AND_UNDER_1_YEAR_BACKDATED("X99", "Hvis fom dato i varighet er lik start dato på sykdomtilfelle og første konsultasjon er mer enn 8 dager fra start dato men ikke over et år",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("BACKDATED_MORE_THEN_8_DAYS_AND_UNDER_1_YEAR_BACKDATED")),
    BACKDATED_MORE_THEN_3_YEARS("X99", "Sykmeldinges fom-dato er mer enn 3 år tilbake i tid.",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("BACKDATED_MORE_THEN_3_YEARS")),
    PRE_DATED("X99", "Hvis sykmeldingen er fremdatert mer enn 30 dager etter konsultasjonsdato/signaturdato avvises meldingen.",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("PRE_DATED")),
    END_DATE("X99", "Hvis sykmeldingens sluttdato er mer enn ett år frem i tid, avvises meldingen.",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("END_DATE")),
    RECEIVED_DATE_BEFORE_PROCESSED_DATE("X99", "Hvis behandletdato er etter dato for mottak av meldingen avvises meldingen",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("RECEIVED_DATE_BEFORE_PROCESSED_DATE")),
    PENDING_SICK_LEAVE_COMBINED("X99", "Hvis avventende sykmelding er funnet og det finnes mer enn en periode",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("PENDING_SICK_LEAVE_COMBINED")),
    MISSING_INSPILL_TIL_ARBEIDSGIVER("X99", "Hvis innspill til arbeidsgiver om tilrettelegging i pkt 4.1.3 ikke er utfylt ved avventende sykmelding avvises meldingen",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("MISSING_INSPILL_TIL_ARBEIDSGIVER")),
    PENDING_PERIOD_OUTSIDE_OF_EMPLOYER_PAID("X99", "Hvis avventende sykmelding benyttes utover i arbeidsgiverperioden på 16 kalenderdager, avvises meldingen.",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("PENDING_PERIOD_OUTSIDE_OF_EMPLOYER_PAID")),
    TOO_MANY_TREATMENT_DAYS("X99", "Hvis antall dager oppgitt for behandlingsdager periode er for høyt i forhold til periodens lengde avvises meldingen. Mer enn en dag per uke er for høyt. 1 dag per påbegynt uke.",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("TOO_MANY_TREATMENT_DAYS")),
    PARTIAL_SICK_LEAVE_PERCENTAGE_TO_LOW("X99", "Hvis sykmeldingsgrad er mindre enn 20% for gradert sykmelding, avvises meldingen",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("PARTIAL_SICK_LEAVE_PERCENTAGE_TO_LOW")),
    PARTIAL_SICK_LEAVE_TOO_HIGH_PERCENTAGE("X99", "Hvis sykmeldingsgrad er høyere enn 99% for delvis sykmelding avvises meldingen",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("PARTIAL_SICK_LEAVE_TOO_HIGH_PERCENTAGE")),
    BACKDATING_SYKMELDING_EXTENSION("X99", "Fom-dato i ny sykmelding som er en forlengelse kan maks være tilbakedatert 1 mnd fra signaturdato. Skal telles.",
            "2.16.578.1.12.4.1.1.8221", RuleInfo("BACKDATING_SYKMELDING_EXTENSION")),
}

fun findApprecError(listRuleinfo: List<RuleInfo>): List<ApprecError> = ApprecError.values().filter { listRuleinfo.contains(it.ruleinfo) }
