name: "Deploy unleash api token"
on:
  push:
    paths:
      - unleash.yaml
      - .github/workflows/deploy-unleash.yaml
jobs:
  deploy-unleash-api-token:
    if: github.ref == 'refs/heads/main'
    name: Deploy to dev and prod
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: deploy to dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: unleash.yaml
          VAR: environment=development
      - name: deploy to prod
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: unleash.yaml
          VAR: environment=production
