name: Deploy app to dev and prod
on:
  push:
    paths-ignore:
      - .github/workflows/deploy-unleash.yaml
      - unleash.yaml

permissions:
  actions: read
  contents: write
  security-events: write
  packages: write
  id-token: write

jobs:
  jar-app:
    uses: navikt/teamsykmelding-github-actions-workflows/.github/workflows/jar-app-21.yaml@main
    secrets: inherit
    with:
      app: syfosmmottak
